// export your constants
const types = {
  BUTTON_CLICK: 'BUTTON_CLICK',
  LOAD_BEGIN: 'LOAD_BEGIN',
  LOAD_COMPLETE: 'LOAD_COMPLETE',
  LOAD_POSTS: 'LOAD_POSTS',
  LOAD_POSTS_SUCCESS: 'LOAD_POSTS_SUCCESS',
  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  LOAD_COMMENTS_SUCCESS: 'LOAD_COMMENTS_SUCCESS'
};

export default types;
